export interface IndiaMarketplace {
  slug: string;
  name: string;
  category: string;
  audience: string;
  sellerType: string;
  commission: string;
  moq: string;
  strength: string;
  ideal: string;
  onboardingTime: string;
  description: string;
  requirements: string[];
  tips: string[];
}

export const indiaMarketplaces: IndiaMarketplace[] = [
  {
    slug: 'myntra',
    name: 'Myntra',
    category: 'Fashion & Lifestyle',
    audience: 'Urban millennials & Gen Z, premium fashion buyers',
    sellerType: 'Invite-only brand onboarding',
    commission: '18–25% (category dependent)',
    moq: '50 styles minimum, 6 pieces per style',
    strength: 'Highest fashion intent traffic in India · 60M+ active users',
    ideal: 'Established D2C fashion brands with strong visual identity',
    onboardingTime: '4–8 weeks (includes brand vetting)',
    description: 'Myntra is India\'s leading fashion marketplace with over 60 million active users. It is the aspirational destination for fashion-forward Indian consumers, particularly in the 18–35 age group. Myntra\'s invite-only model means stricter brand quality standards, but significantly higher average order values and better brand positioning than general marketplaces.',
    requirements: ['GSTIN registration', 'Trademark registration (TM/R)', 'Minimum 50 styles in catalog', 'White background images (minimum 4 angles)', 'Size chart in inches and centimeters', 'Fiber content and care labels on all garments'],
    tips: ['Apply through the Myntra Seller Portal and expect a 2–3 week vetting process', 'Myntra End of Reason Sale (EORS) is the single biggest sales event — plan inventory 3 months in advance', 'Myntra Studio and Live features drive significantly higher engagement than static listings'],
  },
  {
    slug: 'ajio',
    name: 'Ajio',
    category: 'Fashion & Lifestyle',
    audience: 'Tier 1 & Tier 2 fashion buyers, value-premium segment',
    sellerType: 'Invite-only & open seller portal',
    commission: '20–28% (category dependent)',
    moq: '30 styles minimum for brand onboarding',
    strength: 'Reliance-backed with strong Tier 2 & 3 city penetration',
    ideal: 'Mid-market and premium Indian fashion brands',
    onboardingTime: '3–6 weeks',
    description: 'Ajio, backed by Reliance Retail, is one of India\'s fastest-growing fashion marketplaces. It combines a curated fashion marketplace with its own private labels, creating strong brand awareness. Ajio\'s reach into Tier 2 and Tier 3 cities — powered by Reliance\'s offline JioMart network — gives brands access to customers that Myntra and Amazon struggle to reach.',
    requirements: ['GSTIN', 'Trademark or brand authorization letter', 'Minimum catalog of 30 styles', 'Pure white background images', 'Ajio-format size charts', 'FSSAI (for food-related products)'],
    tips: ['Ajio Business (B2B) is a separate platform for wholesale — useful for high-volume sellers', 'Ajio World section features international and premium brands at higher price points', 'Festival sales on Ajio drive 5–8x normal daily sales volumes'],
  },
  {
    slug: 'amazon-india',
    name: 'Amazon India',
    category: 'General Marketplace (Strong in Fashion)',
    audience: 'All segments — broadest reach across India',
    sellerType: 'Open seller registration',
    commission: '8–17% (fashion: 12–17%)',
    moq: 'No minimum — start with 1 SKU',
    strength: 'Largest product catalog · Prime delivery network · 200M+ users',
    ideal: 'All fashion brands — especially those scaling with FBA',
    onboardingTime: '3–7 days (seller account)',
    description: 'Amazon India is the largest e-commerce marketplace in India by seller count and product variety. While not fashion-exclusive like Myntra, Amazon\'s unmatched logistics (FBA), Prime member base, and advertising platform make it essential for any D2C brand. Amazon Brand Registry, A+ content, and Sponsored Ads give serious brands tools to dominate their category.',
    requirements: ['GSTIN', 'PAN card', 'Bank account in India', 'Category approval (for restricted categories)', 'Trademark for Brand Registry (recommended)'],
    tips: ['Amazon Brand Registry unlocks A+ content, Sponsored Brands ads, and Brand Store — apply as early as possible', 'FBA (Fulfilled by Amazon) improves conversion rates by 15–30% due to Prime badge and faster delivery', 'Amazon\'s Great Indian Festival (October) is the largest sales event — plan 4 months in advance'],
  },
  {
    slug: 'flipkart',
    name: 'Flipkart',
    category: 'General Marketplace (Strong in Fashion)',
    audience: 'Value-conscious and Tier 2/3 city buyers',
    sellerType: 'Open seller registration',
    commission: '10–20% (fashion)',
    moq: 'No minimum',
    strength: 'Walmart-backed · Strong Tier 2/3 reach · Flipkart Fashion vertical',
    ideal: 'Value-to-mid-market fashion brands targeting broad India reach',
    onboardingTime: '3–7 days',
    description: 'Flipkart, backed by Walmart, is India\'s second-largest e-commerce marketplace with dominant share in Tier 2 and Tier 3 cities. Flipkart Fashion is a dedicated vertical with 150M+ products. While Flipkart\'s average order value is lower than Myntra, the sheer volume of buyers makes it essential for brands targeting mass-market India.',
    requirements: ['GSTIN', 'PAN card', 'Bank account', 'Category approval for restricted items'],
    tips: ['Flipkart\'s Big Billion Days (October) is the equivalent of Amazon\'s Great Indian Festival — inventory planning is critical', 'Flipkart Assured (their FBA equivalent) improves delivery speeds and conversion rates', 'Myntra and Flipkart share backend infrastructure — joint listing optimization benefits both'],
  },
  {
    slug: 'nykaa-fashion',
    name: 'Nykaa Fashion',
    category: 'Premium Fashion & Lifestyle',
    audience: 'Urban women, premium and aspirational buyers',
    sellerType: 'Invite-only for brands',
    commission: '25–35%',
    moq: '30+ styles recommended',
    strength: 'Premium women\'s fashion · High AOV · Loyal beauty-to-fashion crossover audience',
    ideal: 'Women\'s fashion brands with strong visual identity and premium pricing',
    onboardingTime: '4–8 weeks',
    description: 'Nykaa Fashion is the fashion vertical of Nykaa — India\'s leading beauty platform. It has successfully transferred Nykaa\'s loyal, premium urban female audience to fashion, making it ideal for women\'s apparel, ethnic wear, loungewear, and accessories brands that target the 25–45 urban professional segment. Commission rates are higher, but so are AOVs.',
    requirements: ['Brand with clear women\'s positioning', 'Strong visual identity and photography', 'GSTIN and trademark', 'Minimum catalog of lifestyle or fashion products'],
    tips: ['Nykaa Fashion x Myntra cross-listing is common for premium brands — build catalog once, optimize for both', 'Nykaa\'s Pink Friday Sale is the biggest event of the year — plan 3 months ahead', 'Styling content and editorial shoots perform significantly better on Nykaa than basic white-background images'],
  },
  {
    slug: 'meesho',
    name: 'Meesho',
    category: 'Value Fashion & Social Commerce',
    audience: 'Price-sensitive buyers, Tier 2–5 cities, women resellers',
    sellerType: 'Open seller registration',
    commission: '0–2% (exceptionally low)',
    moq: 'No minimum',
    strength: 'Zero commission model · Massive reseller network · Deep Tier 3/4/5 penetration',
    ideal: 'Value-priced fashion, ethnic wear, and accessories brands',
    onboardingTime: '1–3 days',
    description: 'Meesho operates with near-zero commission and a massive reseller network, making it the dominant platform for value fashion in India\'s Tier 3, 4, and 5 cities. Over 120 million users shop on Meesho, primarily women buying ethnic wear, kurtis, sarees, and affordable fashion. The platform\'s reseller model amplifies product reach organically.',
    requirements: ['GSTIN', 'PAN', 'Bank account', 'Lowest possible pricing (Meesho buyers are very price-sensitive)'],
    tips: ['Meesho works best for products priced under ₹500 — premium brands should not prioritize this platform', 'Ethnic wear, kurtis, and sarees perform exceptionally well', 'Meesho\'s promotional boost program (Meesho Ads) is cost-effective for scaling volume'],
  },
  {
    slug: 'snapdeal',
    name: 'Snapdeal',
    category: 'Value General Marketplace',
    audience: 'Tier 2/3 value buyers',
    sellerType: 'Open seller registration',
    commission: '10–18%',
    moq: 'No minimum',
    strength: 'Strong in value apparel · Tier 2/3 reach',
    ideal: 'Value-priced fashion and accessories brands',
    onboardingTime: '3–5 days',
    description: 'Snapdeal is India\'s third-largest general marketplace with a strong focus on value and Tier 2/3 city buyers. While its market share has declined relative to Amazon and Flipkart, it remains a relevant distribution channel for value fashion — particularly ethnic wear, men\'s basics, and accessories in the ₹200–800 price range.',
    requirements: ['GSTIN', 'PAN', 'Bank account'],
    tips: ['Snapdeal is best used as a supplementary channel, not a primary one', 'Pricing must be aggressive to compete — Snapdeal buyers are highly price-sensitive', 'Focus on high-volume, low-margin products rather than premium positioning'],
  },
  {
    slug: 'tata-cliq',
    name: 'Tata CLiQ',
    category: 'Premium & Luxury Fashion',
    audience: 'Affluent urban buyers, premium brand seekers',
    sellerType: 'Invite-only, curated brand selection',
    commission: '18–30%',
    moq: 'Premium quality standards required',
    strength: 'Tata Group backing · Authentic luxury guarantee · No counterfeit risk',
    ideal: 'Premium and luxury fashion brands, designer labels',
    onboardingTime: '4–10 weeks',
    description: 'Tata CLiQ Luxury is India\'s premier platform for authenticated luxury and premium fashion. Backed by the Tata Group\'s reputation for trust, it attracts affluent Indian buyers seeking guaranteed authentic luxury products. For premium Indian fashion brands, CLiQ\'s positioning alongside international luxury houses provides powerful brand association.',
    requirements: ['Strong brand positioning and visual identity', 'Premium pricing (entry price point ₹2,000+)', 'Tata vetting process including product quality audit', 'GSTIN and trademark'],
    tips: ['CLiQ Luxury and CLiQ Fashion are separate verticals — apply to the one matching your price point', 'Tata CLiQ\'s return policy is strict but customers trust it — lower return fraud vs. general marketplaces', 'Editorial content and brand storytelling are essential on CLiQ — it is not a price-driven platform'],
  },
  {
    slug: 'craftsvilla',
    name: 'Craftsvilla',
    category: 'Ethnic & Handloom Fashion',
    audience: 'Buyers of traditional Indian fashion, NRI shoppers',
    sellerType: 'Open with quality vetting',
    commission: '20–30%',
    moq: 'Varies by category',
    strength: 'Ethnic wear specialist · NRI and diaspora reach · Artisan-friendly',
    ideal: 'Ethnic wear, handloom, artisan fashion, and saree brands',
    onboardingTime: '2–4 weeks',
    description: 'Craftsvilla is India\'s specialized marketplace for ethnic, handloom, and traditional fashion — sarees, salwar suits, lehengas, and artisan accessories. It has a strong NRI and diaspora audience shopping from the US, UK, Canada, and Australia. For ethnic fashion brands, Craftsvilla\'s targeted audience delivers better conversion than general marketplaces.',
    requirements: ['Product must be ethnic, handloom, or traditional Indian fashion', 'Strong product photography', 'GSTIN'],
    tips: ['NRI and diaspora buyers on Craftsvilla have higher AOV and lower return rates', 'Diwali, Navratri, and wedding season are peak selling periods — plan inventory accordingly', 'Handloom and GI-tagged products get featured placement and premium positioning'],
  },
  {
    slug: 'limeroad',
    name: 'LimeRoad',
    category: 'Women\'s Fashion',
    audience: 'Young urban women, fashion-forward buyers',
    sellerType: 'Open seller registration',
    commission: '20–28%',
    moq: 'No minimum',
    strength: 'Social commerce features · Strong women\'s fashion community',
    ideal: 'Women\'s fashion brands targeting 18–30 urban segment',
    onboardingTime: '1–2 weeks',
    description: 'LimeRoad is a women\'s fashion marketplace with strong social commerce and community features — users create scrapbooks and style boards, creating organic discovery for fashion brands. While smaller than Myntra, LimeRoad\'s engaged community model drives discovery through peer recommendations rather than paid advertising.',
    requirements: ['GSTIN', 'Women\'s fashion product focus', 'Good product photography'],
    tips: ['LimeRoad\'s Scrapbook feature drives organic product discovery — invest in lifestyle and styled images', 'Community engagement (responding to style boards and saves) improves organic ranking', 'LimeRoad works well as a supplementary channel alongside Myntra and Ajio'],
  },
  {
    slug: 'jabong',
    name: 'Jabong (Myntra)',
    category: 'Fashion & Lifestyle',
    audience: 'Myntra\'s extended reach',
    sellerType: 'Through Myntra seller account',
    commission: 'Same as Myntra',
    moq: 'Same as Myntra',
    strength: 'Automatic reach extension for Myntra sellers',
    ideal: 'All Myntra sellers get automatic Jabong listing',
    onboardingTime: 'Automatic with Myntra',
    description: 'Jabong, now fully integrated into Myntra\'s platform, provides automatic listing distribution for brands on Myntra. Sellers do not need separate onboarding — products listed on Myntra appear on Jabong automatically. It extends reach to a slightly older demographic than core Myntra buyers.',
    requirements: ['Active Myntra seller account'],
    tips: ['No separate action required — focus on Myntra optimization and Jabong benefits automatically', 'Jabong-specific promotions are rare — Myntra campaigns cover both platforms'],
  },
  {
    slug: 'voonik',
    name: 'Voonik',
    category: 'Women\'s Fashion',
    audience: 'Value women\'s fashion buyers',
    sellerType: 'Open seller registration',
    commission: '15–25%',
    moq: 'No minimum',
    strength: 'AI-based personal styling engine',
    ideal: 'Women\'s fashion brands with diverse size ranges',
    onboardingTime: '1–2 weeks',
    description: 'Voonik is a women\'s fashion marketplace that uses AI-based personal styling recommendations. Its algorithm matches products to buyer body type and style preferences, improving conversion for brands with strong size diversity and inclusive sizing.',
    requirements: ['GSTIN', 'Women\'s product focus', 'Size-inclusive catalog recommended'],
    tips: ['Complete size attribute data improves Voonik\'s algorithm matching and increases visibility', 'Works well as a supplementary channel for women\'s ethnic and western wear'],
  },
  {
    slug: 'paytm-mall',
    name: 'Paytm Mall',
    category: 'General Marketplace',
    audience: 'Paytm Wallet users, Tier 1 & 2 buyers',
    sellerType: 'Open seller registration',
    commission: '5–12%',
    moq: 'No minimum',
    strength: 'Low commission · Paytm user base integration',
    ideal: 'Supplementary channel for brands already on Amazon/Flipkart',
    onboardingTime: '3–5 days',
    description: 'Paytm Mall integrates e-commerce with Paytm\'s massive digital payments user base. While its fashion selection is not as curated as dedicated fashion platforms, it offers lower commissions and access to Paytm\'s payment-first user base.',
    requirements: ['GSTIN', 'PAN'],
    tips: ['Paytm Mall works best as a supplementary channel', 'Cashback and wallet offers drive significant conversion — participate in Paytm promotional campaigns'],
  },
  {
    slug: 'shopclues',
    name: 'ShopClues',
    category: 'Value General Marketplace',
    audience: 'Value buyers, Tier 3/4 cities',
    sellerType: 'Open seller registration',
    commission: '8–15%',
    moq: 'No minimum',
    strength: 'Low price-point market · High volume potential',
    ideal: 'Value fashion and accessories brands',
    onboardingTime: '2–5 days',
    description: 'ShopClues serves the value end of India\'s e-commerce market with a focus on Tier 3 and 4 city buyers. It is best suited for fashion and accessories brands competing on price rather than premium positioning.',
    requirements: ['GSTIN', 'PAN', 'Bank account'],
    tips: ['ShopClues Sunday Flea Market events drive significant traffic spikes', 'Pricing must undercut Amazon and Flipkart to gain traction'],
  },
  {
    slug: 'glowroad',
    name: 'GlowRoad',
    category: 'Social Commerce Reseller Platform',
    audience: 'Women resellers, Tier 2/3 buyers via resellers',
    sellerType: 'Open supplier registration',
    commission: 'Margin-based (suppliers set price)',
    moq: 'No minimum',
    strength: 'Massive reseller network · Zero marketing cost for suppliers',
    ideal: 'Wholesale and high-volume value fashion suppliers',
    onboardingTime: '1–3 days',
    description: 'GlowRoad (now part of Amazon) is a social commerce platform with a large network of women resellers who sell to their WhatsApp and social media contacts. Suppliers list products at wholesale prices and resellers earn margins — creating an organic word-of-mouth distribution network at no marketing cost.',
    requirements: ['Wholesale-friendly pricing', 'GSTIN', 'High-volume production capability'],
    tips: ['List products with clear wholesale pricing and good images — resellers choose based on margin potential', 'High-turnover categories like kurtis and fashion accessories perform best'],
  },
];

export function getMarketplaceBySlug(slug: string): IndiaMarketplace | undefined {
  return indiaMarketplaces.find((m) => m.slug === slug);
}
