export interface USMarketplace {
  slug: string;
  name: string;
  category: string;
  audience: string;
  sellerType: string;
  commission: string;
  moq: string;
  strength: string;
  ideal: string;
  onboardingTime: string;
  description: string;
  requirements: string[];
  tips: string[];
}

export const usMarketplaces: USMarketplace[] = [
  {
    slug: 'amazon',
    name: 'Amazon.com',
    category: 'General Marketplace (Dominant in Fashion)',
    audience: '200M+ Prime members · Broadest US demographic reach',
    sellerType: 'Open seller registration (Professional account)',
    commission: '8–17% referral fee (fashion: 12–17%)',
    moq: 'No minimum — start with 1 SKU',
    strength: 'Largest US marketplace · Prime delivery · FBA fulfillment · Sponsored Ads',
    ideal: 'All fashion brands — mandatory for any serious US e-commerce strategy',
    onboardingTime: '3–7 days (seller account) · 2–4 weeks (Brand Registry)',
    description: 'Amazon.com is the undisputed largest US e-commerce marketplace — over 60% of US product searches start on Amazon. For India-made fashion brands entering the US, Amazon is the highest-priority channel. FBA (Fulfillment by Amazon) handles storage, packaging, and Prime-speed delivery, while Sponsored Products and Sponsored Brands ads accelerate discovery.',
    requirements: ['Government-issued ID or business registration documents', 'US bank account or international bank that Amazon supports', 'Valid credit card', 'Tax information (W-9 for US entity, W-8BEN for foreign entity)', 'Product images meeting Amazon\'s standards (pure white background, 2000px+)'],
    tips: ['Amazon Brand Registry (requires active US or India trademark) unlocks A+ content, Sponsored Brands, and brand protection tools', 'FBA dramatically improves conversion rate — Prime badge increases purchase intent by 25–40%', 'Amazon\'s Great Indian Festival equivalent is Prime Day (July) + Holiday Season (Nov–Dec) — plan inventory 3–4 months ahead', 'A+ Content (formerly EBC) improves conversion by 3–10% — build it for your top 20 ASINs first'],
  },
  {
    slug: 'walmart',
    name: 'Walmart Marketplace',
    category: 'General Marketplace',
    audience: '120M+ monthly visitors · Value and mid-market US buyers',
    sellerType: 'Application-based (approved sellers only)',
    commission: '8–20% (category dependent)',
    moq: 'No minimum',
    strength: 'Second-largest US marketplace · Walmart.com + in-store pickup · Walmart+ members',
    ideal: 'Established brands with proven Amazon track record; mid-market pricing',
    onboardingTime: '2–4 weeks (application and approval)',
    description: 'Walmart Marketplace is the second-largest US e-commerce platform with 120M+ monthly visitors and growing. Unlike Amazon, Walmart requires seller application approval — it vets brands for quality and category fit. But once approved, Walmart sellers benefit from lower competition, lower CAC than Amazon, and integration with Walmart\'s 4,700+ physical stores through in-store pickup.',
    requirements: ['US business entity (LLC or Corporation) OR US EIN for foreign sellers', 'US bank account', 'Active website or selling history on another marketplace', 'Professional product images', 'US tax ID (EIN)'],
    tips: ['Walmart Fulfillment Services (WFS) is their FBA equivalent — use it to qualify for 2-day shipping badge', 'Walmart\'s seller competition is lower than Amazon — easier to rank organically in most fashion categories', 'Walmart Connect (their ad platform) is less sophisticated than Amazon Ads but growing fast — start with Sponsored Products'],
  },
  {
    slug: 'etsy',
    name: 'Etsy',
    category: 'Handmade, Vintage & Unique Fashion',
    audience: 'Creative, independent-minded US buyers seeking unique products',
    sellerType: 'Open seller registration',
    commission: '6.5% transaction fee + $0.20 listing fee',
    moq: 'No minimum — list 1 item to start',
    strength: 'Highest-intent buyers for handmade/artisan fashion · India-made products thrive',
    ideal: 'Handmade, artisan, ethnic, boho, or uniquely designed fashion from India',
    onboardingTime: '1–2 days',
    description: 'Etsy is the premier US marketplace for handmade, artisan, and uniquely designed products. India-made fashion — ethnic prints, block prints, handloom, embroidered garments, boho accessories, and artisan jewelry — performs exceptionally well on Etsy. The platform\'s buyers actively seek "Made in India" provenance, often at premium prices compared to generic fashion marketplaces.',
    requirements: ['Active PayPal or Stripe account for payment', 'Clear product descriptions emphasizing handmade/artisan nature', 'High-quality lifestyle photography (white backgrounds perform less well here)', 'Honest shipping timeline communication (India-to-US takes 10–20 days)'],
    tips: ['"Made in India" is a trust signal on Etsy — mention it prominently in listings and shop bio', 'Etsy SEO (tags, titles, descriptions) is entirely separate from Amazon SEO — optimize for Etsy\'s search algorithm', 'Etsy Ads (formerly Promoted Listings) is highly cost-effective for India-made fashion — start with $5–10/day', 'Star Seller badge significantly improves conversion — maintain fast reply time and 5-star reviews from day one'],
  },
  {
    slug: 'nordstrom',
    name: 'Nordstrom',
    category: 'Premium Department Store Marketplace',
    audience: 'Affluent US buyers · Premium fashion shoppers',
    sellerType: 'Invite-only brand partnerships',
    commission: '30–45% (department store margin)',
    moq: 'Typically 12+ units per style per color',
    strength: 'Premium positioning · Affluent customer base · Nordstrom Rack secondary channel',
    ideal: 'Premium Indian fashion brands with strong visual identity and consistent quality',
    onboardingTime: '8–16 weeks (brand vetting and buyer approval)',
    description: 'Nordstrom is the leading US premium department store marketplace. A Nordstrom listing positions your brand alongside established global fashion labels and signals premium quality to US buyers. Nordstrom\'s buyer approval process is rigorous — but brands that qualify gain access to the most affluent US shoppers. Nordstrom Rack is a separate clearance channel for overstocked and discounted inventory.',
    requirements: ['Premium brand positioning and high-quality photography', 'Consistent production quality across all styles', 'US compliance documentation (fiber content, care labels, CPSC)', 'Nordstrom EDI compliance for orders', 'US import history (customs clearance track record)'],
    tips: ['Nordstrom\'s buyers attend trade shows like MAGIC and NY NOW — attend these to get in front of Nordstrom buyers directly', 'Nordstrom.com has a marketplace program separate from wholesale — easier entry point than traditional wholesale', 'Quality control must be flawless — Nordstrom\'s return rate is high and chargebacks for quality issues are common'],
  },
  {
    slug: 'target-plus',
    name: 'Target+',
    category: 'Mass-Market Retailer Marketplace',
    audience: 'Suburban US families and millennials',
    sellerType: 'Invite-only',
    commission: 'Category dependent (15–30%)',
    moq: 'High volume requirements for Target partnership',
    strength: 'Target\'s 30M+ monthly site visitors · Suburban US demographic',
    ideal: 'Established brands ready for mass-market US retail volumes',
    onboardingTime: '3–6 months (including vendor qualification)',
    description: 'Target+ is Target\'s online marketplace extension for third-party sellers. Target\'s 1,900+ US stores and 30M+ monthly website visitors make it one of the most powerful retail channels in the US. Target+ is invite-only and requires significant brand presence and production scale. It is most appropriate for Indian brands that have already established US marketplace success on Amazon and Walmart.',
    requirements: ['Established brand with proven US sales track record', 'High-volume production capacity', 'EDI compliance', 'US liability insurance', 'Full CPSC compliance documentation'],
    tips: ['Target values "on-trend" products heavily — align your product development with Target\'s seasonal trend reports', 'Target\'s Supply Chain and Logistics team has strict compliance requirements — hire a Target compliance specialist', 'Target+ is a long-term goal for Indian fashion brands — build Amazon and Walmart success first'],
  },
  {
    slug: 'tiktok-shop',
    name: 'TikTok Shop',
    category: 'Social Commerce',
    audience: 'US Gen Z and millennials (18–34)',
    sellerType: 'Open seller registration (US entity or approved international)',
    commission: '6% (promotional rate) → 8%',
    moq: 'No minimum',
    strength: 'Shoppable short-form video · Viral discovery potential · Affiliate creator network',
    ideal: 'Trendy fashion brands with strong visual appeal and TikTok content capability',
    onboardingTime: '1–3 days',
    description: 'TikTok Shop is the fastest-growing US social commerce platform. Products that go viral on TikTok can generate tens of thousands of orders in 24 hours. TikTok\'s affiliate creator program allows brands to partner with content creators who earn commission on sales — creating an organic performance marketing channel. Indian fashion brands with unique aesthetics and affordable pricing have performed exceptionally well on TikTok Shop.',
    requirements: ['US business entity or approved international seller status', 'US bank account for payouts', 'Inventory in US warehouse for fast shipping (5–7 days required)', 'TikTok-native product content (short-form video, not static images)'],
    tips: ['TikTok Shop\'s affiliate creator program is the most powerful free marketing tool on the platform — onboard at least 50 creators in your niche', 'Products must ship within 2 days and deliver within 7 days to maintain Good Standing — use a US 3PL warehouse', 'LIVE Shopping events (going live on TikTok with shoppable products) can drive 10–100x normal daily sales'],
  },
  {
    slug: 'shopify',
    name: 'Shopify (D2C Store)',
    category: 'Direct-to-Consumer E-commerce',
    audience: 'US buyers acquired through brand marketing',
    sellerType: 'Independent store setup',
    commission: '0.5–2% transaction fee (on top of payment processing)',
    moq: 'No minimum',
    strength: 'Full brand control · No marketplace competition · Higher margins · Email list ownership',
    ideal: 'All US fashion brands — Shopify is the D2C foundation; marketplaces are supplementary',
    onboardingTime: '2–4 weeks (full setup and optimization)',
    description: 'Shopify is the world\'s leading D2C e-commerce platform, powering 1.7M+ US online stores. While marketplaces like Amazon and Walmart drive discovery, a Shopify store is essential for brand-controlled customer experience, higher margins (no marketplace commission), and email list building. Most successful US fashion brands operate Shopify as their hub and marketplaces as spokes.',
    requirements: ['Shopify subscription ($39–$399/month)', 'Payment gateway (Stripe or PayPal for US)', 'US tax configuration', 'US shipping carrier accounts (USPS, UPS, FedEx)', 'Custom domain'],
    tips: ['Shopify Markets feature allows geographic pricing — show USD prices to US visitors automatically', 'Shopify\'s integration with Amazon, Walmart, and Etsy via apps allows centralized inventory management', 'Build email list from day one — email marketing delivers the highest ROI of any US digital channel (avg 42:1 ROI)'],
  },
  {
    slug: 'ebay',
    name: 'eBay',
    category: 'General Marketplace (Resale & New)',
    audience: 'Value US buyers, collectors, deal-seekers',
    sellerType: 'Open seller registration',
    commission: '13.25% final value fee (fashion)',
    moq: 'No minimum',
    strength: 'Global reach · Low barriers to entry · Good for unique and limited items',
    ideal: 'Supplementary channel for unique, vintage-style, or value fashion items',
    onboardingTime: '1–2 days',
    description: 'eBay remains a significant US marketplace with 135M+ active buyers globally. While it has shifted heavily toward resale and collectibles, new fashion from India — particularly unique ethnic pieces, boho accessories, and artisan jewelry — finds a willing audience on eBay at lower competition than Amazon.',
    requirements: ['eBay seller account (verified)', 'PayPal or bank account for payouts', 'US shipping label printing capability'],
    tips: ['eBay\'s Global Shipping Program allows Indian sellers to ship to a US hub and eBay handles customs — simplifying international fulfillment', 'Fashion items sell better as Buy It Now (fixed price) rather than auction format on eBay', 'eBay\'s promoted listing program can double visibility for a 2–4% fee on sale'],
  },
  {
    slug: 'poshmark',
    name: 'Poshmark',
    category: 'Fashion Resale & Social Commerce',
    audience: 'US fashion-conscious women and resellers',
    sellerType: 'Open seller registration',
    commission: '20% on sales over $15',
    moq: 'No minimum',
    strength: 'High engagement fashion community · New and pre-owned fashion',
    ideal: 'New and premium fashion brands; items with strong visual and brand storytelling',
    onboardingTime: '1 day',
    description: 'Poshmark is a US social fashion marketplace with 80M+ users — primarily fashion-conscious women. While best known for resale, new fashion brands increasingly use Poshmark as a discovery channel. The platform\'s Posh Party events (themed virtual shopping events) create high-intent discovery moments for fashion brands.',
    requirements: ['Poshmark seller account', 'Strong visual photography', 'Active community engagement (sharing, following, commenting)'],
    tips: ['Poshmark requires active community participation to drive sales — it is not a passive listing platform', 'Posh Parties (themed live sales events) drive significant traffic — participate regularly', 'The Poshmark ambassador program increases your content distribution — work toward ambassador status'],
  },
  {
    slug: 'faire',
    name: 'Faire',
    category: 'B2B Wholesale Marketplace',
    audience: 'US independent boutiques and retailers',
    sellerType: 'Brand application required',
    commission: '15% on first orders from new retailers · 25% on reorders',
    moq: 'Varies — typically $100–$500 minimum per retailer order',
    strength: 'Access to 700,000+ US boutiques and retailers · Net 60 payment terms',
    ideal: 'Fashion brands ready to scale wholesale into US independent retail',
    onboardingTime: '1–2 weeks (application and approval)',
    description: 'Faire is the leading B2B wholesale marketplace in the US, connecting brands to 700,000+ independent boutiques and retailers across the country. For Indian fashion brands, Faire opens the door to US wholesale without the complexity of trade shows or direct retailer outreach. Faire offers Net 60 payment terms to retailers (Faire pays the brand immediately) and free returns on first orders.',
    requirements: ['Brand account on Faire', 'Wholesale pricing (typically 2.5–3x cost price)', 'Professional brand packaging (hang tags, brand labels)', 'Minimum of 15–20 distinct SKUs to build a compelling wholesale collection'],
    tips: ['Faire\'s algorithm rewards fast shipping and low return rates — these metrics are public to retailers', 'Set your wholesale minimum at $150–$250 for independent boutiques (lower than traditional wholesale minimums)', 'Faire\'s Editorial features high-performing brands — work toward features by maintaining strong retailer metrics'],
  },
  {
    slug: 'sephora',
    name: 'Sephora US',
    category: 'Beauty & Wellness Marketplace',
    audience: 'Premium US beauty and wellness buyers',
    sellerType: 'Invite-only brand partnerships',
    commission: '35–50% (standard beauty retail margin)',
    moq: 'High volume requirements',
    strength: 'Premium beauty positioning · Sephora\'s engaged loyalty program',
    ideal: 'Indian beauty, wellness, and fashion-adjacent brands (scarves, accessories) targeting premium US',
    onboardingTime: '3–6 months (brand vetting)',
    description: 'Sephora US is the leading premium beauty marketplace in America. For Indian brands with beauty, wellness, or fashion-adjacent products (printed scarves, artisan jewelry, yoga wear), Sephora provides access to the most beauty-engaged US shoppers. The Sephora Accelerate program specifically supports BIPOC founders including South Asian-owned brands.',
    requirements: ['Premium brand positioning', 'Strong brand story and founder narrative', 'US compliance for beauty/cosmetic products (FDA registration)', 'Production scale to meet Sephora volume requirements'],
    tips: ['Sephora Accelerate is a brand incubator program that can fast-track Sephora access for BIPOC founders', 'Sephora\'s Beauty Insider loyalty program means high repeat purchase rates for brands that earn customer loyalty', 'Start with Sephora.com marketplace before targeting in-store placement'],
  },
  {
    slug: 'instagram-shopping',
    name: 'Instagram Shopping',
    category: 'Social Commerce',
    audience: 'US fashion and lifestyle buyers (18–44)',
    sellerType: 'Available to eligible US business accounts',
    commission: '5% per shipment (selling fee)',
    moq: 'No minimum',
    strength: 'Visual discovery · Direct purchase from content · Influencer shoppable posts',
    ideal: 'Visually strong fashion brands with Instagram content strategy',
    onboardingTime: '1–3 days (setup) · 3–5 days (catalog review)',
    description: 'Instagram Shopping integrates your product catalog directly into Instagram\'s visual feed — enabling users to purchase directly from posts, Stories, and Reels. For fashion brands with strong visual content, Instagram Shopping creates a seamless path from discovery to purchase. Shoppable influencer posts significantly amplify reach without paid advertising.',
    requirements: ['Instagram Business account', 'Facebook Shop (connected)', 'Commerce-eligible products (fashion is included)', 'US Shopify or e-commerce store for product catalog feed'],
    tips: ['Tag products in every Reel and Story — shoppable content consistently outperforms non-shoppable', 'Instagram Shopping and Facebook Shops share the same catalog — set up once, sell on both', 'Checkout on Instagram (allowing purchase without leaving the app) is available to US-based sellers — prioritize this for best conversion'],
  },
  {
    slug: 'google-shopping',
    name: 'Google Shopping',
    category: 'Search-Based Product Discovery',
    audience: 'High-intent US buyers searching for specific products',
    sellerType: 'Available to all Google Merchant Center accounts',
    commission: 'Free listings available · Paid through Google Ads budget',
    moq: 'No minimum',
    strength: 'Highest purchase-intent traffic · Appears in Google search results',
    ideal: 'All US fashion brands — complementary to Amazon and Shopify',
    onboardingTime: '1–3 days (Merchant Center setup)',
    description: 'Google Shopping displays your products directly in Google Search results when users search for specific items. Unlike Amazon (which is a closed ecosystem), Google Shopping reaches buyers who haven\'t yet decided where to purchase — making it a high-intent acquisition channel. Free Listings (organic Google Shopping) and Performance Max campaigns drive both discovery and direct sales.',
    requirements: ['Google Merchant Center account', 'Product feed (from Shopify, WooCommerce, or manual)', 'US business address or US-based website', 'Accurate pricing and availability data'],
    tips: ['Free Listings on Google Shopping are available to all Merchant Center accounts — enable them immediately', 'Performance Max campaigns (Google\'s AI-driven ad type) outperform standard Shopping campaigns for fashion', 'High-quality images are critical — Google Shopping is a visual search engine; hero images drive clicks'],
  },
  {
    slug: 'anthropologie',
    name: 'Anthropologie',
    category: 'Premium Bohemian Fashion Marketplace',
    audience: 'Affluent US women (25–45) with bohemian aesthetic',
    sellerType: 'Brand buyer approval required',
    commission: 'Wholesale margin (typically 50% of retail)',
    moq: 'Typically 6–12 units per style',
    strength: 'Premium boho positioning · Loyal customer base · Anthropologie.com + 200 stores',
    ideal: 'Indian boho, ethnic-inspired, artisan, or premium fashion brands',
    onboardingTime: '3–6 months (buyer approval process)',
    description: 'Anthropologie is the leading US premium bohemian lifestyle retailer, beloved by affluent American women for its unique, globally-inspired aesthetic. Indian fashion brands — particularly those with block prints, hand-embroidery, artisan techniques, or boho-meets-contemporary design — align naturally with Anthropologie\'s buyer and aesthetic. Anthropologie\'s buyers actively source from Indian artisan communities.',
    requirements: ['Strong brand story with artisan or handcraft narrative', 'Premium quality and consistent production', 'US-compliant labeling and packaging', 'Professional brand lookbook and line sheets'],
    tips: ['Anthropologie buyers attend MAGIC Las Vegas and NY NOW trade shows — these are the primary sourcing events', 'Your brand story and origin narrative is as important as the product — Anthropologie buyers love India\'s craft traditions', 'Start with Anthropologie.com marketplace (easier entry) before targeting wholesale to stores'],
  },
  {
    slug: 'revolve',
    name: 'Revolve',
    category: 'Premium Contemporary Fashion',
    audience: 'US Gen Z and millennial women (18–35) · Influencer-connected buyers',
    sellerType: 'Brand application and buyer approval',
    commission: 'Wholesale margin (50% of retail)',
    moq: 'Varies by brand',
    strength: 'Influencer marketing machine · 3.7M Instagram followers · Premium positioning',
    ideal: 'Contemporary, trend-forward Indian fashion brands with premium pricing',
    onboardingTime: '4–8 weeks',
    description: 'Revolve is one of the US\'s most influential fashion platforms for the millennial and Gen Z audience. Known for its powerful influencer-marketing machine and its annual Revolve Festival at Coachella, Revolve positions brands next to Lovers + Friends, For Love & Lemons, and other premium contemporary labels. Indian brands with strong trend relevance and premium aesthetics can build significant US brand equity through Revolve.',
    requirements: ['Contemporary fashion focus (not traditional ethnic wear)', 'Premium pricing ($100+ average retail)', 'Strong brand identity and photography', 'Consistent seasonal collection cadence'],
    tips: ['Revolve\'s influencer program is the key to the platform — brief at least 5 Revolve-connected influencers on your brand', 'Revolve buyers attend MAGIC and Coterie trade shows — prepare a strong brand presentation', 'Revolve\'s FWRD division (ultra-luxury) is a separate and harder-to-access tier'],
  },
];

export function getUSMarketplaceBySlug(slug: string): USMarketplace | undefined {
  return usMarketplaces.find((m) => m.slug === slug);
}
